### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by asb** [ucb-bar/plsi#2]
Hi Palmer. This project looks incredibly interesting - I was curious what the intended license is?

**Comment by palmer-dabbelt** [comment]
What license would you like?

From my understanding of how this works, everything I release here has to pass through the BSD license at some point, but since that's such a permissive license I can pretty much do whatever I want.  I usually re-license software under the LGPL, but I was thinking of just leaving all this stuff as BSD because hardware people are scared of the GPL.

**Comment by asb** [comment]
As you say, I'd imagine BSD would get the widest possible audience. It would also make it easier for hardware projects which are already using a permissive license to import the system either in whole or in part to their source tree, without worrying about complicating the licensing situation.

**Comment by palmer-dabbelt** [comment]
Ya, I was kind of figuring the GPL would be a bad idea here.  What do you think about this one: http://choosealicense.com/licenses/bsd-2-clause/ ?  I'm assuming fewer clauses are better.

**Comment by asb** [comment]
2-clause or 3-clause BSD, or indeed the MIT license are pretty much functionally identical. I don't know what the rules you have on open-sourcing things at Berkeley (e.g. if you are the copyright holder here, or if UCB has a claim). 2-clause BSD is nice and easy, I suppose an argument could be made for favouring consistency with the 3-clause BSD used by rocket, spike, Chisel etc.

**Comment by palmer-dabbelt** [comment]
I'm going with consistency.  https://github.com/ucb-bar/plsi/commit/710cd8f4f1027b1b3ca84471f59ee1eacacf069f
